name: Daily Commit by 24ds3000008@ds.study.iitm.ac.in  # Shown for scheduled runs

on:
  workflow_dispatch:
    run-name: Manual Commit by 24ds3000008@ds.study.iitm.ac.in  # ✅ Explicit run name for manual runs

  schedule:
    - cron: '0 4 * * *'  # ✅ Runs daily at 4 AM UTC

permissions:
  contents: write

jobs:
  commit:
    name: Commit by 24ds3000008@ds.study.iitm.ac.in  # ✅ Shows in job UI for all runs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git Identity
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "24ds3000008@ds.study.iitm.ac.in"

      - name: Make a Change
        run: |
          echo "Last run by 24ds3000008@ds.study.iitm.ac.in at $(date)" > last_run.txt

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMITTER_NAME: "GitHub Action"
          GIT_COMMITTER_EMAIL: "24ds3000008@ds.study.iitm.ac.in"
        run: |
          git add last_run.txt
          git commit \
            --author="GitHub Action <24ds3000008@ds.study.iitm.ac.in>" \
            -m "Commit by 24ds3000008@ds.study.iitm.ac.in at $(date)" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
