name: Daily Commit

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # Daily at 04:00 UTC

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "24ds3000008@ds.study.iitm.ac.in"

      - name: Make a Change
        run: |
          echo "Last run: $(date)" > last_run.txt

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add last_run.txt
          git commit -m "Automated daily commit at $(date)" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
