name: Daily Commit by 24ds3000008@ds.study.iitm.ac.in

on:
  push:
    branches:
      - main
    # ✅ Custom run name for push
    run-name: Daily Commit by 24ds3000008@ds.study.iitm.ac.in

  workflow_dispatch:
    # ✅ Custom run name for manual run
    run-name: Daily Commit by 24ds3000008@ds.study.iitm.ac.in

  schedule:
    - cron: '0 4 * * *'  # Runs daily at 04:00 UTC
    # ⚠️ `run-name:` not yet supported under schedule

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git Identity
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "24ds3000008@ds.study.iitm.ac.in"

      - name: Make a Change
        run: |
          echo "Last run: $(date)" > last_run.txt

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMITTER_NAME: "GitHub Action"
          GIT_COMMITTER_EMAIL: "24ds3000008@ds.study.iitm.ac.in"
        run: |
          git add last_run.txt
          git commit \
            --author="GitHub Action <24ds3000008@ds.study.iitm.ac.in>" \
            -m "Automated daily commit at $(date) by 24ds3000008@ds.study.iitm.ac.in" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
